package org.foedusprogramme.alexandrite.sdk.plugin

import org.foedusprogramme.alexandrite.sdk.config.ConfigSectionSpec
import org.foedusprogramme.alexandrite.sdk.di.container.Binding

/** What one plugin contributes, generated by the Alexandrite KSP processor and never written by hand. */
public interface PluginIndex {
    public val info: PluginInfo

    /** The dot-separated path of the plugin's config. */
    public val configRoot: String

    public fun configSections(): List<ConfigSectionSpec<*>>

    public fun bindings(): List<Binding<*>>

    public companion object {
        /** The resource that lists the index classes of a jar. */
        public val SERVICE_FILE: String = "META-INF/services/${PluginIndex::class.java.name}"

        /** The resource that describes the plugin [id]. */
        public fun descriptorPath(id: String): String = "META-INF/alexandrite/$id.json"
    }
}
